"""Initial migration

Revision ID: 7e0cb3fd95c4
Revises: 
Create Date: 2025-11-22 22:55:46.661935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e0cb3fd95c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=True),
    sa.Column('completada', sa.Boolean(), nullable=True),
    sa.Column('prioridad', sa.String(length=10), nullable=True),
    sa.Column('tipo', sa.String(length=15), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('group_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###
